apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: trino-worker
  labels:
    app: trino-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trino-worker
  template:
    metadata:
      labels:
        app: trino-worker
    spec:
      containers:
        - name: trino-worker
          image: apache/custom-trino:2.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 3Gi
              cpu: 2
            limits:
              memory: 3Gi
              cpu: 2
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: trino-worker-config
              mountPath: /opt/trino/etc/
            - name: trino-coordinator-catalog-config
              mountPath: /opt/trino/etc/catalog/
      volumes:
        - name: trino-worker-config
          configMap:
            name: trino-worker-config
        - name: trino-coordinator-catalog-config
          configMap:
            name: trino-coordinator-catalog-config