apiVersion: v1
kind: ConfigMap
metadata:
  name: trino-coordinator-config
data:
  config.properties: |
    coordinator=true
    http-server.http.port=8080
    discovery.uri=http://trino-headless:8080
    node-scheduler.include-coordinator=false
    task.concurrency=1
    join-distribution-type=PARTITIONED
    memory.heap-headroom-per-node=1GB

  jvm.config: |
    -Xmx2G
    -Xms1G
    -XX:+UseG1GC
    -XX:InitialRAMPercentage=80
    -XX:MaxRAMPercentage=80
    -XX:G1HeapRegionSize=32M
    -XX:+ExplicitGCInvokesConcurrent
    -XX:+ExitOnOutOfMemoryError
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:-OmitStackTraceInFastThrow
    -XX:ReservedCodeCacheSize=512M
    -XX:PerMethodRecompilationCutoff=10000
    -XX:PerBytecodeRecompilationCutoff=10000
    -Djdk.attach.allowAttachSelf=true
    -Djdk.nio.maxCachedBufferSize=2000000
    -Dfile.encoding=UTF-8
    # Allow loading dynamic agent used by JOL
    -XX:+EnableDynamicAgentLoading

  node.properties: |
    node.environment=dev
    node.data-dir=/var/trino/data
  
  log.properties: |
    io.trino=DEBUG