apiVersion: v1
kind: ConfigMap
metadata:
  name: trino-coordinator-catalog-config
data:
  jdbccatalog.properties: |
    connector.name=iceberg
    iceberg.catalog.type=jdbc
    iceberg.jdbc-catalog.catalog-name=data   
    iceberg.jdbc-catalog.driver-class=org.postgresql.Driver
    iceberg.jdbc-catalog.connection-url=jdbc:postgresql://postgres:5432/iceberg
    iceberg.jdbc-catalog.connection-user=
    iceberg.jdbc-catalog.connection-password=
    iceberg.jdbc-catalog.default-warehouse-dir=s3a://iceberg-data/warehouse
    fs.native-s3.enabled=true
    s3.path-style-access=true
    s3.region=us-east-1
    s3.endpoint=http://minio-service:9000
    s3.aws-access-key=
    s3.aws-secret-key=