apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - name: api
      port: 9000
      protocol: TCP
    - name: web
      port: 9090
  selector:
    app: minio